apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly90bmVtbzY1bGR0OlczTHI2d1hGNHJEVndBdnlAY2x1c3RlcjAucTJ1cmJzdC5tb25nb2RiLm5ldC9Kb2JQb3J0YWw=
  USE_SHARDING: dHJ1ZQ==
  SECRET_KEY: eW91cl9zZWNyZXRfa2V5
  CLOUD_NAME: ZGN4bWNlM2Zm
  API_KEY: NTU1NDU0MTg2NjkzMjU5
  API_SECRET: dGYxdWlCQ2NmNHFkQmVWS1hPdXhVcWRGM0k0
  PORT: ODA4MA==
  BASE_URL: aHR0cHM6Ly8zNC44MS4xMjEuMTAx
  FRONTEND_URL: aHR0cHM6Ly9qb2JtYXJrZXQuZnVu
  VITE_API_URL: aHR0cHM6Ly9qb2JtYXJrZXQuZnVuL2FwaS92MQ==
  VITE_FRONTEND_URL: aHR0cHM6Ly9qb2JtYXJrZXQuZnVu
  GOOGLE_CLIENT_ID: MTA1MTc2NDI0ODY4OC1raXYzcHRsbGIxaGNsNjFmcG91a3M4cXJvM3RhOHNsLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  GOOGLE_CLIENT_SECRET: R09DU1BYLUVnM040ZC1lRm9fSlA0dXQzWjBMV01jWk5lNTY=
  SECRET_ENCRYPTION_KEY: MWE4ZDM4OTkyMWFhNjcwYjIxZDVhM2RiNTBkMGM3NzlhNGU4NjU2MjMyOWYxMzFkZjVjNTVjYzZlYWM3MjYwZA==
  NODE_ENV: cHJvZHVjdGlvbg==
  OPENAI_API_KEY: c2stcHJvai00VU5LaThncmpTUHJETmEzUTFLSjF2THBHME9EUTY0ZFhVNzlNWUhKQlo0QkhxUmFLNTY1WkEwc0RiUTRiSXMzSjNtbzE1ZkhKMVQzQmxia0ZKMk0ta3RNWUJLSmxBMjlnak1acFNVSjBETkVUdE9QTEd6THdYZmtvTTNlZHBGNDFjX2JKeU1wR19oRTNwNk94SEtmNWZDNC1PRUE=
  RATE_LIMIT_WINDOW_MS: OTAwMDAw
  RATE_LIMIT_MAX: MTAw
  AUTH_RATE_LIMIT_WINDOW_MS: OTAwMDAw
  AUTH_RATE_LIMIT_MAX: MTA=
  CACHE_TTL: MzAw
  COOKIE_DOMAIN: am9ibWFya2V0LmZ1bg==
  OAUTH_CALLBACK_URL: aHR0cHM6Ly9qb2JtYXJrZXQuZnVuL2FwaS92MS91c2VyL2F1dGgvZ29vZ2xlL2NhbGxiYWNr
  REFRESH_TOKEN_SECRET: eW91ci1yZWZyZXNoLXRva2VuLXNlY3JldC1rZXk=