apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repository.credentials: |
    - url: https://github.com/Tnemo65/JobPortal
      passwordSecret:
        name: git-creds
        key: password
      usernameSecret:
        name: git-creds
        key: username
