apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/empyrean-harbor-456906-s2/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: NODE_ENV
              value: "production"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SESSION_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-oauth-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-oauth-secret
                  key: GOOGLE_CLIENT_SECRET
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-uri
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: extra-app-secrets
                  key: API_KEY

            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: extra-app-secrets
                  key: API_SECRET

            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: extra-app-secrets
                  key: CLOUD_NAME

            - name: SECRET_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: extra-app-secrets
                  key: SECRET_ENCRYPTION_KEY
          readinessProbe:
            httpGet:
              path: /api/v1/job
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5