apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/empyrean-harbor-456906-s2/backend:26a30d3d-3faa-4119-832d-7fca4fc3f832
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PORT
            - name: NODE_ENV
              value: "production"
            - name: DISABLE_SECURE_COOKIES
              value: "true"
            - name: SECURE_COOKIES
              value: "false"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: API_SECRET
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLOUD_NAME
            - name: SECRET_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_ENCRYPTION_KEY
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: BASE_URL
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: FRONTEND_URL
            - name: USE_SHARDING
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: USE_SHARDING
            - name: OAUTH_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OAUTH_CALLBACK_URL
            - name: COOKIE_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: COOKIE_DOMAIN
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REFRESH_TOKEN_SECRET
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_API_KEY
            - name: RATE_LIMIT_WINDOW_MS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RATE_LIMIT_WINDOW_MS
            - name: RATE_LIMIT_MAX
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RATE_LIMIT_MAX
            - name: AUTH_RATE_LIMIT_WINDOW_MS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AUTH_RATE_LIMIT_WINDOW_MS
            - name: AUTH_RATE_LIMIT_MAX
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AUTH_RATE_LIMIT_MAX
            - name: CACHE_TTL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CACHE_TTL
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
