apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=gcr.io/empyrean-harbor-456906-s2/backend
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/empyrean-harbor-456906-s2/backend:6a1027d6-81c6-4823-b9f1-cab151bbd55a
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PORT
            - name: NODE_ENV
              value: "production"
            - name: DISABLE_SECURE_COOKIES
              value: "true"
            - name: SECURE_COOKIES
              value: "false"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: API_SECRET
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLOUD_NAME
            - name: SECRET_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_ENCRYPTION_KEY
            - name: BASE_URL
              value: "http://34.81.121.101"
            - name: FRONTEND_URL
              value: "http://jobmarket.fun"
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_URL
            - name: USE_SHARDING
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: USE_SHARDING
            - name: USE_REDIS_CACHE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: USE_REDIS_CACHE
            - name: USE_REDIS_SESSIONS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: USE_REDIS_SESSIONS
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            