apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/empyrean-harbor-456906-s2/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: NODE_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /api/v1/job
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
