apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 8080
  # type: LoadBalancer
  type: ClusterIP