steps:
  # Install backend dependencies
  - name: 'node:18'
    dir: 'backend'
    entrypoint: 'npm'
    args: ['install']
    id: 'backend-install'
    
  # Build backend docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: ['build', '-t', 'gcr.io/empyrean-harbor-456906-s2/backend:latest', '.']
    id: 'backend-build'
    waitFor: ['backend-install']

  # Push backend to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/empyrean-harbor-456906-s2/backend:latest']
    id: 'backend-push'
    waitFor: ['backend-build']

  # Install frontend dependencies
  - name: 'node:18'
    dir: 'frontend'
    entrypoint: 'npm'
    args: ['install']
    id: 'frontend-install'
    
  # Fix permissions for vite
  - name: 'node:18'
    dir: 'frontend'
    entrypoint: 'chmod'
    args: ['-R', '755', './node_modules/.bin/']
    id: 'fix-permissions'
    waitFor: ['frontend-install']
    
  # Build frontend docker image with production build
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'
    args: ['build', '-t', 'gcr.io/empyrean-harbor-456906-s2/frontend:latest', '.']
    id: 'frontend-docker-build'
    waitFor: ['fix-permissions']

  # Push frontend to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/empyrean-harbor-456906-s2/frontend:latest']
    id: 'frontend-push'
    waitFor: ['frontend-docker-build']

  # Add version tag to image for Argo CD detection
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        docker tag gcr.io/empyrean-harbor-456906-s2/backend:latest gcr.io/empyrean-harbor-456906-s2/backend:$TIMESTAMP
        docker tag gcr.io/empyrean-harbor-456906-s2/frontend:latest gcr.io/empyrean-harbor-456906-s2/frontend:$TIMESTAMP
        docker push gcr.io/empyrean-harbor-456906-s2/backend:$TIMESTAMP
        docker push gcr.io/empyrean-harbor-456906-s2/frontend:$TIMESTAMP
    id: 'tag-images'
    waitFor: ['backend-push', 'frontend-push']

images:
  - 'gcr.io/empyrean-harbor-456906-s2/backend:latest'
  - 'gcr.io/empyrean-harbor-456906-s2/frontend:latest'

timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY