steps:
  # Install backend dependencies
  - name: 'node:18'
    dir: 'backend'
    entrypoint: 'npm'
    args: ['install']
    id: 'backend-install'
    
  # Build backend docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: ['build', '-t', 'gcr.io/empyrean-harbor-456906-s2/backend:latest', '.']
    id: 'backend-build'
    waitFor: ['backend-install']  # Đã thay đổi từ 'backend-test' thành 'backend-install'

  # Push backend to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/empyrean-harbor-456906-s2/backend:latest']
    id: 'backend-push'
    waitFor: ['backend-build']

  # Install frontend dependencies
  - name: 'node:18'
    dir: 'frontend'
    entrypoint: 'npm'
    args: ['install']
    id: 'frontend-install'

  # Fix permissions
  - name: 'node:18'
    dir: 'frontend'
    entrypoint: 'chmod'
    args: ['-R', '755', './node_modules/.bin/']
    id: 'fix-permissions'
    waitFor: ['frontend-install']

  # Build frontend (production build)
  - name: 'node:18'
    dir: 'frontend'
    entrypoint: 'npm'
    args: ['run', 'build']
    id: 'frontend-build'
    waitFor: ['frontend-install']
    
  # Build frontend docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'
    args: ['build', '-t', 'gcr.io/empyrean-harbor-456906-s2/frontend:latest', '.']
    id: 'frontend-docker-build'
    waitFor: ['frontend-build']

  # Push frontend to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/empyrean-harbor-456906-s2/frontend:latest']
    id: 'frontend-push'
    waitFor: ['frontend-docker-build']

  # Deploy to Cloud Run (backend)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'backend-service'
    - '--image=gcr.io/empyrean-harbor-456906-s2/backend:latest'
    - '--region=us-central1'
    - '--platform=managed'
    - '--port=8080'
    - '--allow-unauthenticated'
    - '--set-env-vars=MONGO_URI=mongodb+srv://tnemo65ldt:W3Lr6wXF4rDVwAvy@cluster0.q2urbst.mongodb.net/JobPortal,SECRET_KEY=your_secret_key,CLOUD_NAME=dcxmce3ff,API_KEY=555454186693259,API_SECRET=tf1uiBCcf4qdBeVKXOuxUqdF3I4,PORT=8080,FRONTEND_URL=https://frontend-service-url,USE_SHARDING=true,GOOGLE_CLIENT_ID=50744604192-kqpeapspiuv2csk72lhia6vf64afe06b.apps.googleusercontent.com,GOOGLE_CLIENT_SECRET=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,SECRET_ENCRYPTION_KEY=1a8d389921aa670b21d5a3db50d0c779a4e86562329f131df5c55cc6eac7260d,NODE_ENV=production'
    waitFor: ['backend-push']
    
  # Deploy to Cloud Run (frontend)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'frontend-service'
    - '--image=gcr.io/empyrean-harbor-456906-s2/frontend:latest'
    - '--region=us-central1'
    - '--platform=managed'
    - '--port=80'
    - '--allow-unauthenticated'
    waitFor: ['frontend-push']

images:
  - 'gcr.io/empyrean-harbor-456906-s2/backend:latest'
  - 'gcr.io/empyrean-harbor-456906-s2/frontend:latest'

timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY