apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  # type: LoadBalancer
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: frontend
