apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=gcr.io/empyrean-harbor-456906-s2/frontend
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-05-16T19:05:00+07:00"
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: nginx
                path: custom-nginx.conf
      containers:
        - name: frontend
          image: gcr.io/empyrean-harbor-456906-s2/frontend:e3922f4a-938b-4229-8f3a-6915aeda1401
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/custom.conf
              subPath: custom-nginx.conf
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: PORT
              value: "3000"
            - name: VITE_API_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: VITE_API_URL
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: BASE_URL
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NODE_ENV
            - name: VITE_FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: VITE_FRONTEND_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
