apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-05-16T19:05:00+07:00"
    spec:
      containers:
        - name: frontend
          image: gcr.io/empyrean-harbor-456906-s2/frontend:26a30d3d-3faa-4119-832d-7fca4fc3f832
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: PORT
              value: "3000"
            - name: VITE_API_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: VITE_API_URL
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: BASE_URL
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NODE_ENV
            - name: VITE_FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: VITE_FRONTEND_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
